### ISSUE TITLE
Unicode in filenames makes the program crash

### ISSUE THREAD

**Issue by noiob** [Lazza/RecuperaBit#113]
```
Traceback (most recent call last):
  File "main.py", line 374, in <module>
    main()
  File "main.py", line 371, in main
    interpret(cmd, arguments, parts, shorthands, args.outputdir)
  File "main.py", line 109, in interpret
    print(utils.tree_folder(part.lost))
  File "/usr/lib/pypy3/lib-python/3/encodings/ascii.py", line 22, in encode
    return codecs.ascii_encode(input, self.errors)[0]
UnicodeEncodeError: 'ascii' codec can't encode character '\xc4' in position 1175448: ordinal not in range(128)
```

**Comment by Lazza** [comment]
Have you tried with the standard Python instead of Pypy3? Does the same error occur?

**Comment by noiob** [comment]
I haven't, it didn't occur to me at the time. I can see if I can create a minimal iso reproducing the error
