### ISSUE TITLE
Error while scanning an image (.img): "IndexError: list index out of range"

### ISSUE THREAD

**Issue by SimeoDev** [Lazza/RecuperaBit#13]
I started a scanning an image. The size of image is 465 GB.
I used the latest version of recuperabit.
This is the output:
```

INFO:root:Found NTFS index record at sector 975881640
INFO:root:Found NTFS index record at sector 976504280
INFO:root:Found NTFS index record at sector 976668320
INFO:root:Found NTFS boot sector at sector 976769023
INFO:root:First scan completed
INFO:root:Saving results to settInteressanti.save
INFO:root:Parsing MFT entries
INFO:root:Parsing INDX records
INFO:root:Reading boot sectors
DEBUG:root:Dropping bogus NTFS partition with MFT position 2064 generated by MFT mirror of partition at offset 2048
DEBUG:root:Dropping bogus NTFS partition with MFT position 86432682 generated by MFT mirror of partition at offset 86427520
DEBUG:root:Dropping bogus NTFS partition with MFT position 128554554 generated by MFT mirror of partition at offset 128549392
DEBUG:root:Dropping bogus NTFS partition with MFT position 372031174 generated by MFT mirror of partition at offset 372026012
Traceback (most recent call last):
  File "/opt/RecuperaBit/main.py", line 328, in <module>
    main()
  File "/opt/RecuperaBit/main.py", line 310, in main
    parts.update(scanner.get_partitions())
  File "/opt/RecuperaBit/recuperabit/fs/ntfs.py", line 798, in get_partitions
    relative = datas[0]['runlist'][0]['offset']
IndexError: list index out of range
xubuntu@xubuntu-virtual-machine:/media/xubuntu/Maxtor 1.3 GB$ 
```

**Comment by Lazza** [comment]
Could you try with the updated code?

**Comment by Lazza** [comment]
Closed because no feedback was provided.
