### ISSUE TITLE
ERROR:root:Cannot handle multiple attribute

### ISSUE THREAD

**Issue by EdOOOOO** [Lazza/RecuperaBit#32]
Hi,
Was trying to use your application to recover deleted files/directories on a 320GB hard disk. When i ran the main.py command it output with the below error. Is there something i am missing?

```
DEBUG:root:Found MATCH in positions set([30803328]) with weight 6330 (73.6132108
385%)
INFO:root:Finalizing MFT reconstruction of partition at offset 30801920
INFO:root:Adding extra attributes from $ATTRIBUTE_LIST
ERROR:root:Cannot handle multiple attribute $VOLUME_INFORMATION
Traceback (most recent call last):
  File "./RecuperaBit-master/main.py", line 385, in <module>
    main()
  File "./RecuperaBit-master/main.py", line 367, in main
    parts.update(scanner.get_partitions())
  File "/media/ubuntu/d807d211-57d8-47be-8296-72bd6bba7d0d/paula/RecuperaBit-mas
ter/recuperabit/fs/ntfs.py", line 847, in get_partitions
    self.finalize_reconstruction(part)
  File "/media/ubuntu/d807d211-57d8-47be-8296-72bd6bba7d0d/paula/RecuperaBit-mas
ter/recuperabit/fs/ntfs.py", line 677, in finalize_reconstruction
    self.add_from_attribute_list(parsed, part, node.offset)
  File "/media/ubuntu/d807d211-57d8-47be-8296-72bd6bba7d0d/paula/RecuperaBit-mas
ter/recuperabit/fs/ntfs.py", line 632, in add_from_attribute_list
    _integrate_attribute_list(parsed, part, image)
  File "/media/ubuntu/d807d211-57d8-47be-8296-72bd6bba7d0d/paula/RecuperaBit-mas
ter/recuperabit/fs/ntfs.py", line 250, in _integrate_attribute_list
    child_parsed = parse_file_record(dump)
  File "/media/ubuntu/d807d211-57d8-47be-8296-72bd6bba7d0d/paula/RecuperaBit-mas
ter/recuperabit/fs/ntfs.py", line 150, in parse_file_record
    attributes = _attributes_reader(entry, header['off_first'])
  File "/media/ubuntu/d807d211-57d8-47be-8296-72bd6bba7d0d/paula/RecuperaBit-mas
ter/recuperabit/fs/ntfs.py", line 132, in _attributes_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by Lazza** [comment]
You have encountered a file record which has multiple `$VOLUME_INFORMATION` attributes. This shoud not really be allowed. However, in this case such an error is not so severe to stop the entire program, so I think it might be OK to avoid raising an exception.

I will go on and remove that exception.

**Comment by EdOOOOO** [comment]
Many Thanks, that works perfectly now.
