### ISSUE TITLE
Script fails after attribute list step

### ISSUE THREAD

**Issue by vulcanmike** [Lazza/RecuperaBit#78]
Using the latest Python 3, the script is failing at the point below. (Script fully fails on pypy and Python 2.7 with a "TypeError: category() argument 1 must be unicode, not str" error).

```
INFO:root:Adding extra attributes from $ATTRIBUTE_LIST
Traceback (most recent call last):
  File "/mnt/image/RecuperaBit-master/main.py", line 374, in <module>
    main()
  File "/mnt/image/RecuperaBit-master/main.py", line 357, in main
    parts.update(scanner.get_partitions())
  File "/mnt/image/RecuperaBit-master/recuperabit/fs/ntfs.py", line 836, in get_partitions
    self.finalize_reconstruction(part)
  File "/mnt/image/RecuperaBit-master/recuperabit/fs/ntfs.py", line 672, in finalize_reconstruction
    self.add_from_attribute_list(parsed, part, node.offset)
  File "/mnt/image/RecuperaBit-master/recuperabit/fs/ntfs.py", line 627, in add_from_attribute_list
    _integrate_attribute_list(parsed, part, image)
  File "/mnt/image/RecuperaBit-master/recuperabit/fs/ntfs.py", line 238, in _integrate_attribute_list
    (len(files) == 1 and iter(files).next() == base_record)
AttributeError: 'set_iterator' object has no attribute 'next'
```

**Comment by Lazza** [comment]
Thank you for reporting this issue, I will check it out.

Regarding Python 2, it is not supported anymore.

**Comment by norristh** [comment]
I get the same error with the latest RecuperaBit, and with pypy3 version 7.3.1 and with python3 version 3.8.5.

Is this likely a bug in the latest version of RecuperaBit? Is it worth getting a previous version and trying that? Will the save file be compatible with a previous version?

**Comment by Lazza** [comment]
> Is this likely a bug in the latest version of RecuperaBit?

Yes.

> Is it worth getting a previous version and trying that?

No. Older versions require Python 2. I would use 1.1.3 instead.

> Will the save file be compatible with a previous version?

Probably yes. Currently it is extremely basic and it needs a revamp.
